type: ACTION
language: PYTHON_3
name: Port Auto Description
description: Adds decriptions to ports based on LLDP information.
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to run this script against
    required: true
    hidden: false
